name: Run Python Unit Tests

# Trigger the workflow on pull requests
on:
  pull_request:
    branches:
      - main  # Adjust this if your main branch has a different name

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'  # Specify your required Python version, e.g., '3.10'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Ensure you have a requirements.txt file with necessary dependencies

      # Step 4: Run the unit tests
      - name: Run unit tests
        run: |
          python -m pytest  # Adjust this if you have a different test command or folder

      # Optional: Upload test results as artifacts
      - name: Upload test results (optional)
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-reports/  # If pytest generates a report, store it here
